<?php

namespace InstitutAshariteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BulletinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BulletinRepository extends EntityRepository
{
}
